# Generated by Django 3.2.8 on 2022-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('conditions_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name_condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('practitioner_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('treatments_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('medical', models.CharField(max_length=255)),
                ('surgical', models.CharField(max_length=255)),
                ('radiation', models.CharField(max_length=255)),
                ('chemotherapy', models.CharField(max_length=255)),
                ('other_alternative', models.CharField(max_length=255)),
                ('palliative', models.CharField(max_length=255)),
                ('clinical_trials', models.CharField(max_length=255)),
            ],
        ),
    ]
